package python

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"text/template"
)

const generatedPreamble = "# Code generated by Hostero DevKit; DO NOT EDIT.\n"

var moduleTemplates = map[ModuleKind]*template.Template{
	ModuleInit: newModuleTemplate("init", `{{ .Header }}{{ imports .Imports }}
__all__ = [
{{ range .Exports }}    {{ quote . }},
{{ end }}]
`),
	ModuleEnums: newModuleTemplate("enums", `{{ .Header }}{{ imports .Imports }}{{ range .Enums }}

class {{ .Name }}(str, Enum):
{{ if .Docstring }}{{ docstring .Docstring "    " }}
{{ end }}{{ range .Members }}    {{ .Name }} = {{ quote .Value }}
{{ end }}{{ end }}`),
	ModuleModels: newModuleTemplate("models", `{{ .Header }}{{ imports .Imports }}

@dataclass(frozen=True, slots=True)
class RedirectResponse:
    url: str
{{ range .Models }}

@dataclass(kw_only=True)
class {{ .Name }}:
{{ if .Docstring }}{{ docstring .Docstring "    " }}
{{ end }}{{ if .Fields }}{{ range .Fields }}    {{ .Name }}: {{ .Type }}{{ fieldDefault . }}
{{ end }}
    @classmethod
    def _from_dict(cls, data: Mapping[str, Any]) -> {{ .Name }}:
        return cls(
{{ range .Fields }}            {{ .Name }}={{ fromDictField . }},
{{ end }}        )

    def _to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = {}
{{ range .Fields }}{{ toDictField . }}
{{ end }}        return result
{{ else }}    @classmethod
    def _from_dict(cls, data: Mapping[str, Any]) -> {{ .Name }}:
        return cls()

    def _to_dict(self) -> dict[str, Any]:
        return {}
{{ end }}{{ end }}`),
	ModuleOperations: newModuleTemplate("operations", `{{ .Header }}{{ imports .Imports }}

@dataclass(frozen=True, slots=True)
class Operation:
    operation_id: str
    method: str
    path: str
    required_permissions: tuple[str, ...]
    target_kinds: tuple[str, ...]


OPERATIONS: Final[tuple[Operation, ...]] = (
{{ range .Operations }}    Operation(
        operation_id={{ quote .ID }},
        method={{ quote .Method }},
        path={{ quote .Path }},
        required_permissions={{ stringTuple .Permissions }},
        target_kinds={{ stringTuple .TargetKinds }},
    ),
{{ end }})`),
	ModuleTypes: newModuleTemplate("types", `{{ .Header }}{{ imports .Imports }}{{ range .Aliases }}

{{ .Name }}: TypeAlias = {{ if .QuotedType }}{{ quote .Type }}{{ else }}{{ .Type }}{{ end }}
{{ end }}`),
	ModuleServices: newModuleTemplate("services", `{{ .Header }}{{ imports .Imports }}

_OPERATION_BY_ID = {op.operation_id: op for op in OPERATIONS}


def _filter_none(params: dict[str, Any]) -> dict[str, Any]:
    filtered: dict[str, Any] = {}
    for key, value in params.items():
        if value is not None:
            if isinstance(value, bool):
                filtered[key] = "true" if value else "false"
            else:
                filtered[key] = value
    return filtered


def _prepare_upload(file: Any) -> Any:
    if hasattr(file, "to_httpx_files"):
        return file.to_httpx_files()
    return {"file": file}


def _serialize_body(body: Any) -> Any:
    if body is None:
        return None
    to_dict = getattr(body, "_to_dict", None)
    if callable(to_dict):
        return to_dict()
    return body
{{ range .Services }}

class {{ .Name }}:
{{ if eq .Name "_GeneratedServicesMixin" }}    def __init__(self, client: Any = None) -> None:
        c = client if client is not None else self
{{ if .SubServices }}{{ range .SubServices }}        self.{{ .Name }} = {{ .ClassName }}(c)
{{ end }}{{ end }}{{ else }}    def __init__(self, client: Any) -> None:
        self._client: Any = client
{{ if .SubServices }}{{ range .SubServices }}        self.{{ .Name }} = {{ .ClassName }}(client)
{{ end }}{{ end }}{{ end }}{{ range .Methods }}
    {{ methodSignature . }}
{{ if .Docstring }}{{ docstring .Docstring "        " }}
{{ end }}        path = {{ .PathExpr }}
{{ if .QueryParams }}        params = _filter_none({
{{ range .QueryParams }}            {{ quote .JSONName }}: {{ .Name }},
{{ end }}        })
{{ end }}{{ if .IsMultipart }}        files_payload = _prepare_upload(file)
{{ end }}{{ if .IsRawBody }}        content_payload = content
{{ end }}{{ if .BodyParam }}        json_payload = _serialize_body(body)
{{ end }}{{ if or (eq .ReturnType "None") (eq .SuccessStatus 204) }}        self._client._request(
            {{ quote .HTTPMethod }},
            path,
{{ if .QueryParams }}            params=params,
{{ end }}{{ if .IsMultipart }}            files=files_payload,
{{ end }}{{ if .IsRawBody }}            content=content_payload,
{{ end }}{{ if .BodyParam }}            json=json_payload,
{{ end }}            operation=_OPERATION_BY_ID.get({{ quote .OperationID }}),
        )
        return None
{{ else }}        response = self._client._request(
            {{ quote .HTTPMethod }},
            path,
{{ if .QueryParams }}            params=params,
{{ end }}{{ if .IsMultipart }}            files=files_payload,
{{ end }}{{ if .IsRawBody }}            content=content_payload,
{{ end }}{{ if .BodyParam }}            json=json_payload,
{{ end }}            operation=_OPERATION_BY_ID.get({{ quote .OperationID }}),
        )
{{ methodReturn . }}
{{ end }}{{ end }}{{ end }}`),
}

func Render(document Document, metadata GenerationMetadata) (map[string][]byte, error) {
	if err := validateGenerationMetadata(metadata); err != nil {
		return nil, err
	}
	header := generatedHeader(metadata)

	files := make(map[string][]byte, len(document.Modules))
	for _, module := range document.Modules {
		if _, exists := files[module.Path]; exists {
			return nil, fmt.Errorf("duplicate generated Python path %q", module.Path)
		}
		templateValue, exists := moduleTemplates[module.Kind]
		if !exists {
			return nil, fmt.Errorf("unsupported Python module kind %q", module.Kind)
		}

		var output bytes.Buffer
		if err := templateValue.Execute(&output, templateData{Module: module, Header: header}); err != nil {
			return nil, fmt.Errorf("render Python module %q: %w", module.Path, err)
		}
		contents := strings.TrimRight(output.String(), "\n") + "\n"
		files[module.Path] = []byte(contents)
	}
	return files, nil
}

type templateData struct {
	Module
	Header string
}

func newModuleTemplate(name string, contents string) *template.Template {
	return template.Must(template.New(name).Funcs(template.FuncMap{
		"docstring":       renderDocstring,
		"fieldDefault":    renderFieldDefault,
		"fromDictField":   renderFromDictField,
		"toDictField":     renderToDictField,
		"methodSignature": renderMethodSignature,
		"methodReturn":    renderMethodReturn,
		"imports":         renderImports,
		"join":            strings.Join,
		"quote":           strconv.Quote,
		"stringTuple":     renderStringTuple,
	}).Parse(contents))
}

func renderDocstring(doc string, indent string) string {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return ""
	}
	lines := strings.Split(doc, "\n")
	if len(lines) == 1 {
		return fmt.Sprintf("%s\"\"\"%s\"\"\"", indent, lines[0])
	}
	var output strings.Builder
	output.WriteString(indent)
	output.WriteString("\"\"\"")
	output.WriteString(lines[0])
	output.WriteByte('\n')
	for _, line := range lines[1:] {
		if strings.TrimSpace(line) == "" {
			output.WriteByte('\n')
		} else {
			output.WriteString(indent)
			output.WriteString(line)
			output.WriteByte('\n')
		}
	}
	output.WriteString(indent)
	output.WriteString("\"\"\"")
	return output.String()
}

func renderStringTuple(values []string) string {
	if len(values) == 0 {
		return "()"
	}
	items := make([]string, 0, len(values))
	for _, value := range values {
		items = append(items, strconv.Quote(value))
	}
	return "(" + strings.Join(items, ", ") + ",)"
}

func generatedHeader(metadata GenerationMetadata) string {
	return fmt.Sprintf(
		generatedPreamble+"# devkit: %s\n# OpenAPI source: %s\n# release: %s\n# sha256: %s\n",
		metadata.DevKitVersion,
		metadata.OpenAPISource,
		metadata.Release,
		metadata.SHA256,
	)
}

func validateGenerationMetadata(metadata GenerationMetadata) error {
	values := []struct {
		label string
		value string
	}{
		{label: "DevKit version", value: metadata.DevKitVersion},
		{label: "OpenAPI source", value: metadata.OpenAPISource},
		{label: "release", value: metadata.Release},
		{label: "SHA-256", value: metadata.SHA256},
	}
	for _, item := range values {
		if strings.TrimSpace(item.value) == "" || strings.ContainsAny(item.value, "\r\n") {
			return fmt.Errorf("generation metadata %s is invalid", item.label)
		}
	}
	return nil
}

func renderImports(imports []Import) string {
	var output strings.Builder
	var previous ImportGroup
	for _, importValue := range imports {
		if previous != "" && previous != importValue.Group {
			output.WriteByte('\n')
		}
		if len(importValue.Names) == 0 {
			fmt.Fprintf(&output, "import %s\n", importValue.Module)
		} else {
			fmt.Fprintf(&output, "from %s import %s\n", importValue.Module, strings.Join(importValue.Names, ", "))
		}
		previous = importValue.Group
	}
	return output.String()
}

func renderFieldDefault(fieldValue Field) string {
	if fieldValue.Name == fieldValue.JSONName {
		if fieldValue.Required && !fieldValue.Nullable {
			return ""
		}
		return " = None"
	}

	metadata := "metadata={\"hostero.json_name\": " + strconv.Quote(fieldValue.JSONName) + "}"
	if fieldValue.Required && !fieldValue.Nullable {
		return " = field(" + metadata + ")"
	}
	return " = field(default=None, " + metadata + ")"
}

func renderFromDictField(f Field) string {
	jsonKey := strconv.Quote(f.JSONName)
	switch f.CodecKind {
	case CodecEnum:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("%s(data[%s])", f.TargetType, jsonKey)
		}
		return fmt.Sprintf("%s(data[%s]) if data.get(%s) is not None else None", f.TargetType, jsonKey, jsonKey)
	case CodecModel:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("%s._from_dict(data[%s])", f.TargetType, jsonKey)
		}
		return fmt.Sprintf("%s._from_dict(data[%s]) if data.get(%s) is not None else None", f.TargetType, jsonKey, jsonKey)
	case CodecListModel:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("[%s._from_dict(item) for item in data[%s]]", f.TargetType, jsonKey)
		}
		return fmt.Sprintf("[%s._from_dict(item) for item in data[%s]] if data.get(%s) is not None else None", f.TargetType, jsonKey, jsonKey)
	case CodecListEnum:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("[%s(item) for item in data[%s]]", f.TargetType, jsonKey)
		}
		return fmt.Sprintf("[%s(item) for item in data[%s]] if data.get(%s) is not None else None", f.TargetType, jsonKey, jsonKey)
	case CodecMapModel:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("{k: %s._from_dict(v) for k, v in data[%s].items() if v is not None}", f.TargetType, jsonKey)
		}
		return fmt.Sprintf("{k: %s._from_dict(v) for k, v in data[%s].items() if v is not None} if data.get(%s) is not None else None", f.TargetType, jsonKey, jsonKey)
	default:
		if f.Required && !f.Nullable {
			return fmt.Sprintf("data[%s]", jsonKey)
		}
		return fmt.Sprintf("data.get(%s)", jsonKey)
	}
}

func renderToDictField(f Field) string {
	jsonKey := strconv.Quote(f.JSONName)
	name := f.Name
	switch f.CodecKind {
	case CodecEnum:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = self.%s.value", name, jsonKey, name)
	case CodecModel:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = self.%s._to_dict()", name, jsonKey, name)
	case CodecListModel:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = [item._to_dict() for item in self.%s]", name, jsonKey, name)
	case CodecListEnum:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = [item.value for item in self.%s]", name, jsonKey, name)
	case CodecMapModel:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = {k: v._to_dict() for k, v in self.%s.items()}", name, jsonKey, name)
	default:
		return fmt.Sprintf("        if self.%s is not None:\n            result[%s] = self.%s", name, jsonKey, name)
	}
}

func renderMethodSignature(m ServiceMethod) string {
	params := []string{"self"}
	for _, p := range m.PathParams {
		params = append(params, fmt.Sprintf("%s: %s", p.Name, p.Type))
	}
	hasKwOnly := len(m.QueryParams) > 0 || m.HasBody || m.IsMultipart || m.IsRawBody
	if hasKwOnly {
		params = append(params, "*")
	}
	for _, q := range m.QueryParams {
		defVal := q.DefaultValue
		if !q.Required && defVal == "" {
			defVal = " = None"
		}
		params = append(params, fmt.Sprintf("%s: %s%s", q.Name, q.Type, defVal))
	}
	if m.IsMultipart {
		params = append(params, "file: Upload | Any")
	} else if m.IsRawBody {
		params = append(params, "content: bytes | str")
	} else if m.BodyParam != nil {
		bodyType := m.BodyParam.Type
		if !m.BodyParam.Required {
			params = append(params, fmt.Sprintf("body: %s = None", bodyType))
		} else {
			params = append(params, fmt.Sprintf("body: %s", bodyType))
		}
	}
	return fmt.Sprintf("def %s(%s) -> %s:", m.Name, strings.Join(params, ", "), m.ReturnType)
}

func renderMethodReturn(m ServiceMethod) string {
	if m.SuccessStatus == 302 {
		return "        location = response.headers.get(\"location\")\n" +
			"        if not location:\n" +
			"            raise ApiError(status_code=response.status_code, code=\"MISSING_LOCATION\", detail=\"Missing Location header in redirect response\", operation=_OPERATION_BY_ID.get(" + strconv.Quote(m.OperationID) + "))\n" +
			"        return RedirectResponse(url=location)"
	}
	if m.ReturnType == "None" || m.SuccessStatus == 204 {
		return "        return None"
	}
	if m.IsReturnList {
		return fmt.Sprintf("        return [%s._from_dict(item) for item in response.json()]", m.ReturnModelName)
	}
	if m.IsReturnModel {
		return fmt.Sprintf("        return %s._from_dict(response.json())", m.ReturnModelName)
	}
	return "        return response.json()"
}
