package python

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"text/template"
)

const generatedPreamble = "# Code generated by Hostero DevKit; DO NOT EDIT.\n"

var moduleTemplates = map[ModuleKind]*template.Template{
	ModuleInit: newModuleTemplate("init", `{{ .Header }}{{ imports .Imports }}
__all__ = [
{{ range .Exports }}    {{ quote . }},
{{ end }}]
`),
	ModuleEnums: newModuleTemplate("enums", `{{ .Header }}{{ imports .Imports }}{{ range .Enums }}

class {{ .Name }}(str, Enum):
{{ range .Members }}    {{ .Name }} = {{ quote .Value }}
{{ end }}{{ end }}`),
	ModuleModels: newModuleTemplate("models", `{{ .Header }}{{ imports .Imports }}{{ range .Models }}

@dataclass(kw_only=True)
class {{ .Name }}:
{{ if .Fields }}{{ range .Fields }}    {{ .Name }}: {{ .Type }}{{ fieldDefault . }}
{{ end }}{{ else }}    pass
{{ end }}{{ end }}`),
}

func Render(document Document, metadata GenerationMetadata) (map[string][]byte, error) {
	if err := validateGenerationMetadata(metadata); err != nil {
		return nil, err
	}
	header := generatedHeader(metadata)

	files := make(map[string][]byte, len(document.Modules))
	for _, module := range document.Modules {
		if _, exists := files[module.Path]; exists {
			return nil, fmt.Errorf("duplicate generated Python path %q", module.Path)
		}
		templateValue, exists := moduleTemplates[module.Kind]
		if !exists {
			return nil, fmt.Errorf("unsupported Python module kind %q", module.Kind)
		}

		var output bytes.Buffer
		if err := templateValue.Execute(&output, templateData{Module: module, Header: header}); err != nil {
			return nil, fmt.Errorf("render Python module %q: %w", module.Path, err)
		}
		contents := strings.TrimRight(output.String(), "\n") + "\n"
		files[module.Path] = []byte(contents)
	}
	return files, nil
}

type templateData struct {
	Module
	Header string
}

func newModuleTemplate(name string, contents string) *template.Template {
	return template.Must(template.New(name).Funcs(template.FuncMap{
		"fieldDefault": renderFieldDefault,
		"imports":      renderImports,
		"join":         strings.Join,
		"quote":        strconv.Quote,
	}).Parse(contents))
}

func generatedHeader(metadata GenerationMetadata) string {
	return fmt.Sprintf(
		generatedPreamble+"# devkit: %s\n# OpenAPI source: %s\n# release: %s\n# sha256: %s\n",
		metadata.DevKitVersion,
		metadata.OpenAPISource,
		metadata.Release,
		metadata.SHA256,
	)
}

func validateGenerationMetadata(metadata GenerationMetadata) error {
	values := []struct {
		label string
		value string
	}{
		{label: "DevKit version", value: metadata.DevKitVersion},
		{label: "OpenAPI source", value: metadata.OpenAPISource},
		{label: "release", value: metadata.Release},
		{label: "SHA-256", value: metadata.SHA256},
	}
	for _, item := range values {
		if strings.TrimSpace(item.value) == "" || strings.ContainsAny(item.value, "\r\n") {
			return fmt.Errorf("generation metadata %s is invalid", item.label)
		}
	}
	return nil
}

func renderImports(imports []Import) string {
	var output strings.Builder
	var previous ImportGroup
	for _, importValue := range imports {
		if len(importValue.Names) == 0 {
			continue
		}
		if previous != "" && previous != importValue.Group {
			output.WriteByte('\n')
		}
		fmt.Fprintf(&output, "from %s import %s\n", importValue.Module, strings.Join(importValue.Names, ", "))
		previous = importValue.Group
	}
	return output.String()
}

func renderFieldDefault(fieldValue Field) string {
	if fieldValue.Name == fieldValue.JSONName {
		if fieldValue.Required {
			return ""
		}
		return " = None"
	}

	metadata := "metadata={\"hostero.json_name\": " + strconv.Quote(fieldValue.JSONName) + "}"
	if fieldValue.Required {
		return " = field(" + metadata + ")"
	}
	return " = field(default=None, " + metadata + ")"
}
