# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.30.131845
# sha256: d5d7834ea8211ad101397d1e5fcd68696438447e2c53a3b5bdbc84941af59db4
from enum import Enum


class AllocationProtocol(str, Enum):
    BOTH = "both"
    TCP = "tcp"
    UDP = "udp"


class AxonOperationStatus(str, Enum):
    CANCELLED = "cancelled"
    CANCELLING = "cancelling"
    FAILED = "failed"
    INTERRUPTED = "interrupted"
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"


class CellVariableFieldType(str, Enum):
    BOOLEAN = "boolean"
    NUMBER = "number"
    SELECT = "select"
    TEXT = "text"


class DatabaseEngine(str, Enum):
    MARIADB = "mariadb"
    MYSQL = "mysql"
    POSTGRESQL = "postgresql"


class GameServerBackupComponentKind(str, Enum):
    DATABASE = "database"
    FILES = "files"


class GameServerBackupComponentStatus(str, Enum):
    FAILED = "failed"
    PENDING = "pending"
    SUCCEEDED = "succeeded"


class GameServerBackupRestoreStatus(str, Enum):
    COMPLETED = "completed"
    DOWNLOADING = "downloading"
    EXTRACTING = "extracting"
    FAILED = "failed"
    PARTIAL = "partial"
    QUEUED = "queued"
    RESTARTING = "restarting"
    STOPPING = "stopping"
    SWAPPING = "swapping"
    VALIDATING = "validating"


class GameServerBackupStatus(str, Enum):
    CANCELLED = "cancelled"
    COMPLETED = "completed"
    DELETED = "deleted"
    FAILED = "failed"
    IN_PROGRESS = "in_progress"
    PARTIAL = "partial"
    PENDING = "pending"


class GameServerDomainStatus(str, Enum):
    ACTIVE = "active"
    DELETING = "deleting"
    FAILED = "failed"
    PENDING = "pending"


class GameServerOperationProgressStatus(str, Enum):
    COMPLETED = "completed"
    FAILED = "failed"
    RUNNING = "running"


class GameServerStatus(str, Enum):
    ERROR = "error"
    INSTALL_FAILED = "install_failed"
    INSTALLED = "installed"
    INSTALLING = "installing"
    RESTORING = "restoring"
    RUNNING = "running"
    STARTING = "starting"
    STOPPED = "stopped"
    STOPPING = "stopping"
    SUSPENDED = "suspended"


class InviteStatus(str, Enum):
    ACCEPTED = "accepted"
    DECLINED = "declined"
    EXPIRED = "expired"
    PENDING = "pending"
    REVOKED = "revoked"


class MessageKind(str, Enum):
    SYSTEM = "system"
    USER = "user"


class ScheduleRunStatus(str, Enum):
    DEGRADED = "degraded"
    FAILED = "failed"
    QUEUED = "queued"
    RUNNING = "running"
    SKIPPED = "skipped"
    SUCCEEDED = "succeeded"


class ScheduleStepType(str, Enum):
    BACKUP = "backup"
    COMMAND = "command"
    DELAY = "delay"
    POWER = "power"


class ServerAvailability(str, Enum):
    """Customer-facing availability of a game-server control surface."""

    AVAILABLE = "available"
    NODE_MAINTENANCE = "node_maintenance"
    NODE_UNREACHABLE = "node_unreachable"
    SERVER_UNAVAILABLE = "server_unavailable"


class ServerPermission(str, Enum):
    ACTIVITY_VIEW = "activity.view"
    ALLOCATIONS_UPDATE = "allocations.update"
    ALLOCATIONS_VIEW = "allocations.view"
    BACKUPS_CREATE = "backups.create"
    BACKUPS_DELETE = "backups.delete"
    BACKUPS_DOWNLOAD = "backups.download"
    BACKUPS_RESTORE = "backups.restore"
    BACKUPS_VIEW = "backups.view"
    CONSOLE_ACCESS = "console.access"
    DATABASES_CREATE = "databases.create"
    DATABASES_CREDENTIALS_RESET = "databases.credentials.reset"
    DATABASES_CREDENTIALS_VIEW = "databases.credentials.view"
    DATABASES_DELETE = "databases.delete"
    DATABASES_VIEW = "databases.view"
    DOMAINS_UPDATE = "domains.update"
    DOMAINS_VIEW = "domains.view"
    FILES_DELETE = "files.delete"
    FILES_READ = "files.read"
    FILES_WRITE = "files.write"
    POWER_KILL = "power.kill"
    POWER_REINSTALL = "power.reinstall"
    POWER_RESTART = "power.restart"
    POWER_START = "power.start"
    POWER_STOP = "power.stop"
    SCHEDULES_CREATE = "schedules.create"
    SCHEDULES_DELETE = "schedules.delete"
    SCHEDULES_RUN = "schedules.run"
    SCHEDULES_UPDATE = "schedules.update"
    SCHEDULES_VIEW = "schedules.view"
    SERVER_USAGE_VIEW = "server.usage.view"
    SERVER_VIEW = "server.view"
    SFTP_ACCESS = "sftp.access"
    STARTUP_UPDATE = "startup.update"
    STARTUP_VIEW = "startup.view"
    SUBUSERS_CREATE = "subusers.create"
    SUBUSERS_DELETE = "subusers.delete"
    SUBUSERS_UPDATE = "subusers.update"
    SUBUSERS_VIEW = "subusers.view"
    WEBHOOKS_CREATE = "webhooks.create"
    WEBHOOKS_DELETE = "webhooks.delete"
    WEBHOOKS_UPDATE = "webhooks.update"
    WEBHOOKS_VIEW = "webhooks.view"


class TicketCategory(str, Enum):
    ABUSE = "abuse"
    BILLING = "billing"
    GENERAL = "general"
    OTHER = "other"
    TECHNICAL = "technical"


class TicketParticipantRole(str, Enum):
    ASSIGNEE = "assignee"
    OWNER = "owner"
    PARTICIPANT = "participant"


class TicketPriority(str, Enum):
    HIGH = "high"
    LOW = "low"
    MEDIUM = "medium"
    URGENT = "urgent"


class TicketStatus(str, Enum):
    CLOSED = "closed"
    ON_HOLD = "on_hold"
    OPEN = "open"
    PENDING = "pending"
    RESOLVED = "resolved"
