# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.29.194014
# sha256: dd1c161a1afa03fd4f86ad5486f65fac1c05f26740d3a9bf2ea338fee15402bb
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .enums import (
    AllocationProtocol,
    AxonOperationStatus,
    CellVariableFieldType,
    DatabaseEngine,
    GameServerBackupComponentKind,
    GameServerBackupComponentStatus,
    GameServerBackupRestoreStatus,
    GameServerBackupStatus,
    GameServerDomainStatus,
    GameServerOperationProgressStatus,
    GameServerStatus,
    InviteStatus,
    MessageKind,
    ScheduleRunStatus,
    ScheduleStepType,
    ServerAvailability,
    ServerPermission,
    TicketCategory,
    TicketParticipantRole,
    TicketPriority,
    TicketStatus,
)
from .types import JsonObjectInput, JsonObjectOutput, JsonValueOutput


@dataclass(kw_only=True)
class AxonOperationResource:
    completed_at: str | None
    created_at: str
    error_code: str | None
    error_message: str | None
    id: str
    kind: str
    phase: str | None
    progress_current: int
    progress_is_estimated: bool
    progress_total: int
    result: dict[str, Any]
    revision: int
    status: AxonOperationStatus
    updated_at: str


@dataclass(kw_only=True)
class BodyUploadAttachmentV1TicketsTicketIdMessagesMessageIdAttachmentsPost:
    file: str


@dataclass(kw_only=True)
class CustomerGameAllocationResource:
    allocation_type: str
    id: str
    ip: str
    is_locked: bool
    port: int


@dataclass(kw_only=True)
class ErrorResponse:
    code: str
    detail: Any | None = None


@dataclass(kw_only=True)
class FileCompressRequest:
    paths: list[str] | None = None
    root: str


@dataclass(kw_only=True)
class FileContentsResource:
    content: str


@dataclass(kw_only=True)
class FileCreateDirectoriesRequest:
    paths: list[str]


@dataclass(kw_only=True)
class FileCreateDirectoryRequest:
    path: str


@dataclass(kw_only=True)
class FileDecompressRequest:
    destination_name: str
    dir: str
    file: str


@dataclass(kw_only=True)
class FileDeleteRequest:
    paths: list[str]


@dataclass(kw_only=True)
class FileInfoResource:
    is_dir: bool
    is_symlink: bool
    mime: str
    mode: str
    modified_at: int
    name: str
    size: int


@dataclass(kw_only=True)
class FileListResource:
    files: list[FileInfoResource]
    has_more: bool | None = None
    has_previous: bool | None = None
    next_page_token: str | None = None
    previous_page_token: str | None = None
    total_count: int | None = None


@dataclass(kw_only=True)
class FileRenameRequest:
    from_path: str
    to_path: str


@dataclass(kw_only=True)
class FileSearchResource:
    has_more: bool
    results: list[FileSearchResultResource]


@dataclass(kw_only=True)
class FileSearchResultResource:
    file: FileInfoResource
    path: str
    relevance: int


@dataclass(kw_only=True)
class FileUrlResource:
    expires_at: int
    url: str


@dataclass(kw_only=True)
class GameCatalogDetailResource:
    currency: str
    description: str | None
    event_tokens: dict[str, str] | None = None
    icon_url: str | None
    id: str
    is_popular: bool
    name: str
    offers: list[GameOfferListingResource]
    price_from: int | None
    slug: str
    thumbnail_url: str | None


@dataclass(kw_only=True)
class GameCatalogListItemResource:
    currency: str
    description: str | None
    event_tokens: dict[str, str] | None = None
    icon_url: str | None
    id: str
    is_popular: bool
    name: str
    offer_count: int
    price_from: int | None
    slug: str
    thumbnail_url: str | None


@dataclass(kw_only=True)
class GameOfferCellOptionResource:
    description: str | None
    description_key: str | None
    id: str
    name: str | None
    name_key: str | None
    slug: str


@dataclass(kw_only=True)
class GameOfferFeatureResource:
    icon_key: str
    key: str


@dataclass(kw_only=True)
class GameOfferListingResource:
    additional_allocation_pricing: int | None = None
    additional_backup_pricing: int | None = None
    allowed_additional_allocations: int | None = None
    allowed_additional_backups: int | None = None
    allowed_cell_ids: list[str] | None = None
    badge_label_key: str | None
    cells: list[GameOfferCellOptionResource] | None = None
    default_cell_id: str | None = None
    description_key: str | None
    event_tokens: dict[str, str] | None = None
    features: list[GameOfferFeatureResource] | None = None
    game_feature_keys: list[str] | None = None
    id: str
    is_active: bool
    is_featured: bool
    limit_allocations: int
    limit_backups: int
    limit_cpu: int
    limit_databases: int
    limit_disk_mb: int
    limit_memory_mb: int
    location_id: str | None = None
    marketing_description_key: str | None
    name: str
    pricing: int
    region_id: str | None = None
    required_allocation_types: list[str] | None = None
    slug: str
    sort_order: int
    variant_id: str | None = None


@dataclass(kw_only=True)
class GameServerActivityActorResource:
    id: str | None = None
    is_staff: bool | None = None
    kind: str
    label: str | None = None


@dataclass(kw_only=True)
class GameServerActivityResource:
    action: str
    actor: GameServerActivityActorResource
    created_at: str
    ip_address: str | None
    meta_data: dict[str, JsonValueOutput] | None


@dataclass(kw_only=True)
class GameServerBackupComponentResource:
    engine: DatabaseEngine | None = None
    error_code: str | None = None
    id: str
    kind: GameServerBackupComponentKind
    name: str
    status: GameServerBackupComponentStatus


@dataclass(kw_only=True)
class GameServerBackupCreateRequest:
    include_databases: bool | None = None
    name: str | None = None


@dataclass(kw_only=True)
class GameServerBackupResource:
    checksum: str | None
    completed_at: str | None
    components: list[GameServerBackupComponentResource]
    created_at: str
    error_code: str | None
    id: str
    include_databases: bool
    name: str
    size_bytes: int | None
    status: GameServerBackupStatus


@dataclass(kw_only=True)
class GameServerBackupRestoreProgressResource:
    backup_id: str
    estimated_seconds_remaining: int | None
    files_processed: int
    files_total: int | None
    id: str
    phase_bytes_processed: int
    phase_bytes_total: int | None
    progress_is_estimated: bool
    progress_percent: int | None
    progress_sequence: int
    rate_bytes_per_second: int
    started_at: str
    status: GameServerBackupRestoreStatus
    work_bytes_processed: int
    work_bytes_total: int | None


@dataclass(kw_only=True)
class GameServerBackupRestoreRequest:
    confirm: bool
    database_component_ids: list[str] | None = None
    restore_files: bool | None = None


@dataclass(kw_only=True)
class GameServerBackupSettingsResource:
    exclude_patterns: list[str]


@dataclass(kw_only=True)
class GameServerBackupSettingsUpdateRequest:
    exclude_patterns: list[str] | None = None


@dataclass(kw_only=True)
class GameServerCellSummaryResource:
    name: str
    name_key: str | None
    slug: str


@dataclass(kw_only=True)
class GameServerConsoleTokenResource:
    expires_at: int
    token: str
    ws_url: str


@dataclass(kw_only=True)
class GameServerDatabaseCreateRequest:
    engine: DatabaseEngine
    name: str


@dataclass(kw_only=True)
class GameServerDatabaseDeleteRequest:
    confirm_database_name: str


@dataclass(kw_only=True)
class GameServerDatabaseListItemResource:
    allowed_connections: str
    created_at: str
    database: str
    engine: DatabaseEngine
    host: str
    id: str
    port: int
    username: str


@dataclass(kw_only=True)
class GameServerDatabaseResource:
    allowed_connections: str
    created_at: str
    database: str
    engine: DatabaseEngine
    host: str
    id: str
    password: str
    port: int
    username: str


@dataclass(kw_only=True)
class GameServerDetailResource:
    auto_renew: bool
    availability: ServerAvailability | None = None
    billing_currency: str | None
    capabilities: list[ServerPermission] | None = None
    cell: GameServerCellSummaryResource
    created_at: str
    description: str | None
    docker_image: str
    expires_at: str | None
    features: list[GameServerFeatureResource]
    game: GameServerGameSummaryResource
    id: str
    is_custom_offer: bool
    limits: GameServerLimitsResource
    name: str
    node: GameServerNodeSummaryResource
    offer: GameServerOfferSummaryResource | None
    operation_progress: GameServerOperationProgressResource | None = None
    permissions: list[ServerPermission] | None = None
    price: int
    primary_allocation: GameServerListPrimaryResource | None
    restore: GameServerBackupRestoreProgressResource | None = None
    scheduled_delete_at: str | None
    short_id: str
    status: GameServerStatus
    suspended_at: str | None
    updated_at: str


@dataclass(kw_only=True)
class GameServerFeatureResource:
    configuration: JsonObjectOutput
    key: str


@dataclass(kw_only=True)
class GameServerFolderCreateRequest:
    name: str
    parent_id: str | None = None


@dataclass(kw_only=True)
class GameServerFolderResource:
    id: str
    name: str
    parent_id: str | None
    position: int


@dataclass(kw_only=True)
class GameServerFolderUpdateRequest:
    name: str | None = None
    parent_id: str | None = None
    position: int | None = None


@dataclass(kw_only=True)
class GameServerGameSummaryResource:
    id: str
    name: str
    slug: str


@dataclass(kw_only=True)
class GameServerInviteCreateRequest:
    identifier: str
    permissions: list[ServerPermission]


@dataclass(kw_only=True)
class GameServerLimitsResource:
    cpu: int
    disk_mb: int
    max_allocations: int
    max_backups: int
    max_databases: int
    memory_mb: int
    memory_swap_mb: int


@dataclass(kw_only=True)
class GameServerListItemResource:
    expires_at: str | None
    game_name: str
    id: str
    limits: GameServerListLimitsResource
    name: str
    node_name: str
    permissions: list[ServerPermission] | None = None
    primary_allocation: GameServerListPrimaryResource | None
    scheduled_delete_at: str | None
    short_id: str
    status: GameServerStatus


@dataclass(kw_only=True)
class GameServerListLimitsResource:
    cpu: int
    disk_mb: int
    max_allocations: int
    max_backups: int
    max_databases: int
    memory_mb: int


@dataclass(kw_only=True)
class GameServerListPrimaryResource:
    ip: str
    port: int
    protocol: AllocationProtocol


@dataclass(kw_only=True)
class GameServerNodeSummaryResource:
    name: str


@dataclass(kw_only=True)
class GameServerOfferSummaryResource:
    id: str
    name: str


@dataclass(kw_only=True)
class GameServerOperationProgressResource:
    attempt_id: str | None = None
    estimated_seconds_remaining: int | None = None
    operation: str
    progress_is_estimated: bool
    progress_percent: int | None = None
    sequence: int | None = None
    stage: str
    stage_count: int
    stage_index: int
    stage_progress_percent: int | None = None
    status: GameServerOperationProgressStatus


@dataclass(kw_only=True)
class GameServerScheduleCreateRequest:
    cron: str
    enabled: bool | None = None
    name: str
    retry_delay_seconds: int | None = None
    retry_limit: int | None = None
    steps: list[GameServerScheduleStepRequest]
    timezone: str


@dataclass(kw_only=True)
class GameServerScheduleResource:
    created_at: str
    cron: str
    enabled: bool
    id: str
    last_run_at: str | None
    last_status: ScheduleRunStatus | None
    name: str
    next_run_at: str | None
    retry_delay_seconds: int
    retry_limit: int
    steps: list[GameServerScheduleStepResource]
    timezone: str
    updated_at: str


@dataclass(kw_only=True)
class GameServerScheduleRunResource:
    attempt: int
    created_at: str
    error: str | None
    finished_at: str | None
    id: str
    started_at: str | None
    status: ScheduleRunStatus
    step_runs: list[GameServerScheduleStepRunResource]
    trigger: str


@dataclass(kw_only=True)
class GameServerScheduleStepRequest:
    config: dict[str, Any] | None = None
    continue_on_failure: bool | None = None
    name: str
    step_id: str | None = None
    timeout_seconds: int | None = None
    type: str


@dataclass(kw_only=True)
class GameServerScheduleStepResource:
    config: dict[str, Any]
    continue_on_failure: bool
    id: str
    name: str
    position: int
    timeout_seconds: int | None
    type: ScheduleStepType


@dataclass(kw_only=True)
class GameServerScheduleStepRunResource:
    error: str | None
    finished_at: str | None
    id: str
    name: str
    position: int
    result: dict[str, Any] | None
    started_at: str | None
    status: ScheduleRunStatus
    type: ScheduleStepType


@dataclass(kw_only=True)
class GameServerScheduleUpdateRequest:
    cron: str | None = None
    enabled: bool | None = None
    name: str | None = None
    retry_delay_seconds: int | None = None
    retry_limit: int | None = None
    steps: list[GameServerScheduleStepRequest] | None = None
    timezone: str | None = None


@dataclass(kw_only=True)
class GameServerSftpCredentialsResource:
    auth_methods: list[str]
    host: str
    password: str
    port: int
    rules: list[GameServerSftpRuleResource]
    username: str


@dataclass(kw_only=True)
class GameServerSftpRuleRequest:
    effect: str | None = None
    path: str
    permissions: list[str]
    target_type: str


@dataclass(kw_only=True)
class GameServerSftpRuleResource:
    effect: str
    path: str
    permissions: list[str]
    target_type: str


@dataclass(kw_only=True)
class GameServerSidebarFolderChildResource:
    id: str
    name: str
    position: int
    servers: list[GameServerSidebarServerItem]


@dataclass(kw_only=True)
class GameServerSidebarFolderResource:
    children: list[GameServerSidebarFolderChildResource]
    id: str
    name: str
    position: int
    servers: list[GameServerSidebarServerItem]


@dataclass(kw_only=True)
class GameServerSidebarServerItem:
    id: str
    name: str
    short_id: str


@dataclass(kw_only=True)
class GameServerSidebarTreeResource:
    folders: list[GameServerSidebarFolderResource]
    root_servers: list[GameServerSidebarServerItem]


@dataclass(kw_only=True)
class GameServerStartupDockerImageResource:
    image: str
    label: str | None
    label_key: str | None
    recommended: bool


@dataclass(kw_only=True)
class GameServerStartupSettingsResource:
    docker_image: str
    docker_images: list[GameServerStartupDockerImageResource]
    requires_restart: bool
    startup_argv: list[str]
    startup_command: str
    variables: list[GameServerStartupVariableResource]


@dataclass(kw_only=True)
class GameServerStartupUpdateRequest:
    docker_image: str | None = None
    variables: dict[str, str] | None = None


@dataclass(kw_only=True)
class GameServerStartupVariableOptionResource:
    label_key: str | None
    value: str


@dataclass(kw_only=True)
class GameServerStartupVariableResource:
    default_value: str
    description: str | None
    description_key: str | None
    env_variable: str
    field_type: CellVariableFieldType
    name: str | None
    name_key: str | None
    options: list[GameServerStartupVariableOptionResource] | None
    rules: dict[str, Any]
    user_editable: bool
    value: str


@dataclass(kw_only=True)
class GameServerSubuserResource:
    created_at: str
    id: str
    permissions: list[ServerPermission]
    sftp_rules: list[GameServerSftpRuleResource] | None = None
    updated_at: str
    user: GameServerSubuserUserResource


@dataclass(kw_only=True)
class GameServerSubuserUpdateRequest:
    permissions: list[ServerPermission]
    sftp_rules: list[GameServerSftpRuleRequest] | None = None


@dataclass(kw_only=True)
class GameServerSubuserUserResource:
    email: str | None
    id: str
    username: str


@dataclass(kw_only=True)
class GameServerUpdateRequest:
    name: str


@dataclass(kw_only=True)
class GameServerUsageResource:
    cpu_percent: float
    disk_bytes: int | None
    memory_bytes: int
    memory_limit_bytes: int
    running: bool
    status: str


@dataclass(kw_only=True)
class ManagedDomainOptionResource:
    hostname: str
    id: str


@dataclass(kw_only=True)
class MinecraftInstallerReinstallRequest:
    selection: JsonObjectInput
    wipe: bool | None = None


@dataclass(kw_only=True)
class PaginatedResponseAxonOperationResource:
    has_next: bool
    items: list[AxonOperationResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PaginatedResponseGameServerActivityResource:
    has_next: bool
    items: list[GameServerActivityResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PaginatedResponseGameServerListItemResource:
    has_next: bool
    items: list[GameServerListItemResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PaginatedResponseGameServerScheduleResource:
    has_next: bool
    items: list[GameServerScheduleResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PaginatedResponseGameServerScheduleRunResource:
    has_next: bool
    items: list[GameServerScheduleRunResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PaginatedResponseTicketResource:
    has_next: bool
    items: list[TicketResource]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class RegionResource:
    created_at: str
    id: str
    name: str
    updated_at: str


@dataclass(kw_only=True)
class ServerDomainResource:
    domain_id: str
    error_code: str | None = None
    hostname: str
    id: str
    mode: str | None = None
    prefix: str
    status: GameServerDomainStatus


@dataclass(kw_only=True)
class ServerInviteResource:
    created_at: str
    expires_at: str
    id: str
    identifier: str
    permissions: list[str]
    status: InviteStatus


@dataclass(kw_only=True)
class ServerOverviewItemResource:
    id: str
    name: str
    short_id: str
    status: GameServerStatus


@dataclass(kw_only=True)
class ServerSubdomainRequest:
    domain_id: str | None = None
    prefix: str | None = None


@dataclass(kw_only=True)
class ServersOverviewResource:
    items: list[ServerOverviewItemResource]
    running: int
    stopped: int
    total: int


@dataclass(kw_only=True)
class TicketAttachmentResource:
    content_type: str
    created_at: str
    filename: str
    id: str
    size: int


@dataclass(kw_only=True)
class TicketAuthorResource:
    avatar_hash: str | None = None
    id: str
    username: str


@dataclass(kw_only=True)
class TicketCreateRequest:
    category: TicketCategory | None = None
    priority: TicketPriority | None = None
    reference_id: str | None = None
    reference_type: str | None = None
    subject: str


@dataclass(kw_only=True)
class TicketDetailResource:
    category: TicketCategory
    closed_at: str | None
    created_at: str
    id: str
    participants: list[TicketParticipantResource]
    priority: TicketPriority
    reference_id: str | None
    reference_type: str | None
    status: TicketStatus
    subject: str
    updated_at: str


@dataclass(kw_only=True)
class TicketMessageCreateRequest:
    content: str
    is_internal: bool | None = None
    mentions: list[str] | None = None


@dataclass(kw_only=True)
class TicketMessageResource:
    attachments: list[TicketAttachmentResource]
    author: TicketAuthorResource | None
    content: str
    created_at: str
    id: str
    is_internal: bool
    kind: MessageKind
    metadata: dict[str, JsonValueOutput] | None
    updated_at: str


@dataclass(kw_only=True)
class TicketParticipantResource:
    created_at: str
    id: str
    role: TicketParticipantRole
    user: TicketAuthorResource


@dataclass(kw_only=True)
class TicketResource:
    category: TicketCategory
    closed_at: str | None
    created_at: str
    id: str
    priority: TicketPriority
    reference_id: str | None
    reference_type: str | None
    status: TicketStatus
    subject: str
    updated_at: str


@dataclass(kw_only=True)
class TicketStatusUpdateRequest:
    status: TicketStatus


@dataclass(kw_only=True)
class TicketsOverviewResource:
    open: int


@dataclass(kw_only=True)
class ValidationErrorDetail:
    code: str
    ctx: dict[str, Any] | None = None
    field: str | None


@dataclass(kw_only=True)
class ValidationErrorResponse:
    code: str | None = None
    detail: list[ValidationErrorDetail] | None = None
