# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.30.131845
# sha256: d5d7834ea8211ad101397d1e5fcd68696438447e2c53a3b5bdbc84941af59db4
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .models import (
    GameServerDetailResource,
    GameServerListItemResource,
    PaginatedResponseGameServerListItemResource,
)


class _BoundService:
    def __init__(
        self, service: Any, resource_id: str, path: str, allowed: frozenset[str]
    ) -> None:
        self._service = service
        self._resource_id = resource_id
        self._path = path
        self._allowed = allowed

    def __getattr__(self, name: str) -> Any:
        path = name if not self._path else self._path + "." + name
        value = getattr(self._service, name)
        if callable(value):
            if path not in self._allowed:
                raise AttributeError(name)

            def bound(*args: Any, **kwargs: Any) -> Any:
                return value(self._resource_id, *args, **kwargs)

            return bound
        prefix = path + "."
        if not any(method.startswith(prefix) for method in self._allowed):
            raise AttributeError(name)
        return _BoundService(value, self._resource_id, path, self._allowed)


_GameServer_BOUND_METHODS = frozenset(
    {
        "activity.list",
        "allocations.list",
        "backups.create",
        "backups.delete",
        "backups.download",
        "backups.get_settings",
        "backups.list",
        "backups.restores.create",
        "backups.restores.get_active",
        "backups.update_settings",
        "console.get_token",
        "databases.create",
        "databases.delete",
        "databases.get",
        "databases.list",
        "databases.reset_password",
        "domain.delete",
        "domain.get",
        "domain.list_options",
        "domain.set_subdomain",
        "files.compress.create",
        "files.contents.get",
        "files.contents.write",
        "files.create_directories",
        "files.create_directory",
        "files.decompress.cancel",
        "files.decompress.create",
        "files.decompress.get",
        "files.decompress.get_active",
        "files.delete",
        "files.get_download_url",
        "files.list",
        "files.rename",
        "files.search.cancel",
        "files.search.get",
        "get",
        "invites.create",
        "invites.delete",
        "invites.list",
        "minecraft-installer.list_builds",
        "minecraft-installer.list_engines",
        "minecraft-installer.list_versions",
        "minecraft-installer.reinstall",
        "operations.cancel",
        "operations.get",
        "operations.list",
        "power.kill",
        "power.reinstall",
        "power.restart",
        "power.start",
        "power.stop",
        "schedules.create",
        "schedules.delete",
        "schedules.get",
        "schedules.list",
        "schedules.run",
        "schedules.runs.list",
        "schedules.update",
        "sftp.get_credentials",
        "sftp.rotate_credentials",
        "startup.get",
        "startup.update",
        "subusers.delete",
        "subusers.list",
        "subusers.update",
        "update",
    }
)


@dataclass(frozen=True, slots=True)
class GameServer:
    data: GameServerDetailResource
    _service: Any = field(repr=False, compare=False)

    def __getattr__(self, name: str) -> Any:
        return _BoundService(
            self._service, self.id, "", _GameServer_BOUND_METHODS
        ).__getattr__(name)

    @property
    def auto_renew(self):
        return self.data.auto_renew

    @property
    def availability(self):
        return self.data.availability

    @property
    def billing_currency(self):
        return self.data.billing_currency

    @property
    def capabilities(self):
        return self.data.capabilities

    @property
    def cell(self):
        return self.data.cell

    @property
    def created_at(self):
        return self.data.created_at

    @property
    def description(self):
        return self.data.description

    @property
    def docker_image(self):
        return self.data.docker_image

    @property
    def expires_at(self):
        return self.data.expires_at

    @property
    def features(self):
        return self.data.features

    @property
    def game(self):
        return self.data.game

    @property
    def id(self):
        return self.data.id

    @property
    def is_custom_offer(self):
        return self.data.is_custom_offer

    @property
    def limits(self):
        return self.data.limits

    @property
    def name(self):
        return self.data.name

    @property
    def node(self):
        return self.data.node

    @property
    def offer(self):
        return self.data.offer

    @property
    def operation_progress(self):
        return self.data.operation_progress

    @property
    def permissions(self):
        return self.data.permissions

    @property
    def price(self):
        return self.data.price

    @property
    def primary_allocation(self):
        return self.data.primary_allocation

    @property
    def restore(self):
        return self.data.restore

    @property
    def scheduled_delete_at(self):
        return self.data.scheduled_delete_at

    @property
    def short_id(self):
        return self.data.short_id

    @property
    def status(self):
        return self.data.status

    @property
    def suspended_at(self):
        return self.data.suspended_at

    @property
    def updated_at(self):
        return self.data.updated_at


_GameServerListItem_BOUND_METHODS = frozenset(
    {
        "activity.list",
        "allocations.list",
        "backups.create",
        "backups.delete",
        "backups.download",
        "backups.get_settings",
        "backups.list",
        "backups.restores.create",
        "backups.restores.get_active",
        "backups.update_settings",
        "console.get_token",
        "databases.create",
        "databases.delete",
        "databases.get",
        "databases.list",
        "databases.reset_password",
        "domain.delete",
        "domain.get",
        "domain.list_options",
        "domain.set_subdomain",
        "files.compress.create",
        "files.contents.get",
        "files.contents.write",
        "files.create_directories",
        "files.create_directory",
        "files.decompress.cancel",
        "files.decompress.create",
        "files.decompress.get",
        "files.decompress.get_active",
        "files.delete",
        "files.get_download_url",
        "files.list",
        "files.rename",
        "files.search.cancel",
        "files.search.get",
        "get",
        "invites.create",
        "invites.delete",
        "invites.list",
        "minecraft-installer.list_builds",
        "minecraft-installer.list_engines",
        "minecraft-installer.list_versions",
        "minecraft-installer.reinstall",
        "operations.cancel",
        "operations.get",
        "operations.list",
        "power.kill",
        "power.reinstall",
        "power.restart",
        "power.start",
        "power.stop",
        "schedules.create",
        "schedules.delete",
        "schedules.get",
        "schedules.list",
        "schedules.run",
        "schedules.runs.list",
        "schedules.update",
        "sftp.get_credentials",
        "sftp.rotate_credentials",
        "startup.get",
        "startup.update",
        "subusers.delete",
        "subusers.list",
        "subusers.update",
        "update",
    }
)


@dataclass(frozen=True, slots=True)
class GameServerListItem:
    data: GameServerListItemResource
    _service: Any = field(repr=False, compare=False)

    def __getattr__(self, name: str) -> Any:
        return _BoundService(
            self._service, self.id, "", _GameServerListItem_BOUND_METHODS
        ).__getattr__(name)

    @property
    def expires_at(self):
        return self.data.expires_at

    @property
    def game_name(self):
        return self.data.game_name

    @property
    def id(self):
        return self.data.id

    @property
    def limits(self):
        return self.data.limits

    @property
    def name(self):
        return self.data.name

    @property
    def node_name(self):
        return self.data.node_name

    @property
    def permissions(self):
        return self.data.permissions

    @property
    def primary_allocation(self):
        return self.data.primary_allocation

    @property
    def scheduled_delete_at(self):
        return self.data.scheduled_delete_at

    @property
    def short_id(self):
        return self.data.short_id

    @property
    def status(self):
        return self.data.status


@dataclass(frozen=True, slots=True)
class GameServerPage:
    data: PaginatedResponseGameServerListItemResource
    _service: Any = field(repr=False, compare=False)

    @property
    def items(self) -> list[GameServerListItem]:
        return [
            GameServerListItem(data=item, _service=self._service)
            for item in self.data.items
        ]

    @property
    def has_next(self):
        return self.data.has_next

    @property
    def limit(self):
        return self.data.limit

    @property
    def offset(self):
        return self.data.offset

    @property
    def total(self):
        return self.data.total
