# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.29.215802
# sha256: 6778b119150fbe92110694fb1b25f1480db511c925360b38429c7926e19a010d
from __future__ import annotations

import builtins
from typing import Any
from urllib.parse import quote as _quote_path

from .._upload import Upload
from ..exceptions import ApiError
from .models import (
    AxonOperationResource,
    CustomerGameAllocationResource,
    FileCompressRequest,
    FileContentsResource,
    FileCreateDirectoriesRequest,
    FileCreateDirectoryRequest,
    FileDecompressRequest,
    FileDeleteRequest,
    FileListResource,
    FileRenameRequest,
    FileSearchResource,
    FileUrlResource,
    GameCatalogDetailResource,
    GameCatalogListItemResource,
    GameOfferListingResource,
    GameServerBackupCreateRequest,
    GameServerBackupResource,
    GameServerBackupRestoreProgressResource,
    GameServerBackupRestoreRequest,
    GameServerBackupSettingsResource,
    GameServerBackupSettingsUpdateRequest,
    GameServerConsoleTokenResource,
    GameServerDatabaseCreateRequest,
    GameServerDatabaseDeleteRequest,
    GameServerDatabaseListItemResource,
    GameServerDatabaseResource,
    GameServerDetailResource,
    GameServerFolderCreateRequest,
    GameServerFolderResource,
    GameServerFolderUpdateRequest,
    GameServerInviteCreateRequest,
    GameServerScheduleCreateRequest,
    GameServerScheduleResource,
    GameServerScheduleRunResource,
    GameServerScheduleUpdateRequest,
    GameServerSftpCredentialsResource,
    GameServerSidebarTreeResource,
    GameServerStartupSettingsResource,
    GameServerStartupUpdateRequest,
    GameServerSubuserResource,
    GameServerSubuserUpdateRequest,
    GameServerUpdateRequest,
    GameServerUsageResource,
    ManagedDomainOptionResource,
    MinecraftInstallerReinstallRequest,
    PaginatedResponseAxonOperationResource,
    PaginatedResponseGameServerActivityResource,
    PaginatedResponseGameServerListItemResource,
    PaginatedResponseGameServerScheduleResource,
    PaginatedResponseGameServerScheduleRunResource,
    PaginatedResponseTicketResource,
    RedirectResponse,
    RegionResource,
    ServerDomainResource,
    ServerInviteResource,
    ServersOverviewResource,
    ServerSubdomainRequest,
    TicketAttachmentResource,
    TicketCreateRequest,
    TicketDetailResource,
    TicketMessageCreateRequest,
    TicketMessageResource,
    TicketResource,
    TicketsOverviewResource,
    TicketStatusUpdateRequest,
)
from .operations import OPERATIONS
from .types import JsonObjectOutput

_OPERATION_BY_ID = {op.operation_id: op for op in OPERATIONS}


def _filter_none(params: dict[str, Any]) -> dict[str, Any]:
    filtered: dict[str, Any] = {}
    for key, value in params.items():
        if value is not None:
            if isinstance(value, bool):
                filtered[key] = "true" if value else "false"
            else:
                filtered[key] = value
    return filtered


def _prepare_upload(file: Any) -> Any:
    if hasattr(file, "to_httpx_files"):
        return file.to_httpx_files()
    return {"file": file}


def _serialize_body(body: Any) -> Any:
    if body is None:
        return None
    to_dict = getattr(body, "_to_dict", None)
    if callable(to_dict):
        return to_dict()
    return body


class GameFeaturesMinecraftInstallerService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list_engines(
        self, *, region_id: str, variant_id: str
    ) -> builtins.list[JsonObjectOutput]:
        """List Minecraft engines live from MCJars for the selected offer variant.

        Required permissions:
            - `catalog.read`
        """
        path = "/game-features/minecraft-server-installer/catalog/engines"
        params = _filter_none(
            {
                "region_id": region_id,
                "variant_id": variant_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get(
                "game_features_minecraft_server_installer_catalog_engines_list"
            ),
        )
        return response.json()

    def list_versions(
        self,
        engine: str,
        *,
        include_archived: bool | None = None,
        region_id: str,
        search: str | None = None,
        variant_id: str,
    ) -> builtins.list[JsonObjectOutput]:
        """List compatible versions for the specified engine.

        Required permissions:
            - `catalog.read`
        """
        path = f"/game-features/minecraft-server-installer/catalog/engines/{_quote_path(str(engine), safe='')}/versions"
        params = _filter_none(
            {
                "include_archived": include_archived,
                "region_id": region_id,
                "search": search,
                "variant_id": variant_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get(
                "game_features_minecraft_server_installer_catalog_engines_versions_list"
            ),
        )
        return response.json()

    def list_builds(
        self,
        engine: str,
        version: str,
        *,
        include_archived: bool | None = None,
        region_id: str,
        variant_id: str,
    ) -> builtins.list[JsonObjectOutput]:
        """List compatible builds for the specified engine and version.

        Required permissions:
            - `catalog.read`
        """
        path = f"/game-features/minecraft-server-installer/catalog/engines/{_quote_path(str(engine), safe='')}/versions/{_quote_path(str(version), safe='')}/builds"
        params = _filter_none(
            {
                "include_archived": include_archived,
                "region_id": region_id,
                "variant_id": variant_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get(
                "game_features_minecraft_server_installer_catalog_engines_versions_builds_list"
            ),
        )
        return response.json()


class GameFeaturesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.minecraft_installer = GameFeaturesMinecraftInstallerService(client)


class GamesOffersService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(self, game_id: str) -> builtins.list[GameOfferListingResource]:
        """List active offers for a game, sorted by sort_order.

        Required permissions:
            - `catalog.read`
        """
        path = f"/games/{_quote_path(str(game_id), safe='')}/offers"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("games_offers_list"),
        )
        return [GameOfferListingResource._from_dict(item) for item in response.json()]


class GamesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.offers = GamesOffersService(client)


class OrderGamesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(
        self, *, limit: int | None = None, offset: int | None = None, region_id: str
    ) -> builtins.list[GameCatalogListItemResource]:
        """List active game-server catalog entries with at least one active offer.

        Required permissions:
            - `catalog.read`
        """
        path = "/order/game-servers"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
                "region_id": region_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("order_game_servers_list"),
        )
        return [
            GameCatalogListItemResource._from_dict(item) for item in response.json()
        ]

    def list_regions(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> builtins.list[RegionResource]:
        """List regions selectable in the game-server order flow.

        Required permissions:
            - `catalog.read`
        """
        path = "/order/game-servers/regions"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("order_game_servers_regions_list"),
        )
        return [RegionResource._from_dict(item) for item in response.json()]

    def get(self, game_slug: str, *, region_id: str) -> GameCatalogDetailResource:
        """Return active game details and active offers for the order catalog.

        Required permissions:
            - `catalog.read`
        """
        path = f"/order/game-servers/{_quote_path(str(game_slug), safe='')}"
        params = _filter_none(
            {
                "region_id": region_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("order_game_servers_get"),
        )
        return GameCatalogDetailResource._from_dict(response.json())


class OrderService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.games = OrderGamesService(client)


class ServersActivityService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(
        self,
        server_id: str,
        *,
        actions: builtins.list[str] | None = None,
        days: int | None = None,
        from_date: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort: str | None = None,
        to_date: str | None = None,
    ) -> PaginatedResponseGameServerActivityResource:
        """List game server activity.

        Required permissions:
            - `game_servers.activity.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/activity"
        params = _filter_none(
            {
                "actions": actions,
                "days": days,
                "from_date": from_date,
                "limit": limit,
                "offset": offset,
                "sort": sort,
                "to_date": to_date,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_activity_list"),
        )
        return PaginatedResponseGameServerActivityResource._from_dict(response.json())


class ServersAllocationsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(self, server_id: str) -> builtins.list[CustomerGameAllocationResource]:
        """List network endpoints visible to the authenticated server member.

        Required permissions:
            - `game_servers.allocations.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/allocations"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_allocations_list"),
        )
        return [
            CustomerGameAllocationResource._from_dict(item) for item in response.json()
        ]


class ServersBackupsRestoresService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get_active(
        self, server_id: str
    ) -> GameServerBackupRestoreProgressResource | None:
        """Get active restore.

        Required permissions:
            - `game_servers.view`
        """
        path = (
            f"/servers/{_quote_path(str(server_id), safe='')}/backups/restores/active"
        )
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_backups_restores_active_list"),
        )
        return GameServerBackupRestoreProgressResource._from_dict(response.json())

    def create(
        self,
        server_id: str,
        backup_id: str,
        *,
        body: GameServerBackupRestoreRequest | dict[str, Any],
    ) -> dict[str, str]:
        """Restore backup.

        Required permissions:
            - `game_servers.backups.restore`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups/{_quote_path(str(backup_id), safe='')}/restore"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_backups_restore_create"),
        )
        return response.json()


class ServersBackupsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.restores = ServersBackupsRestoresService(client)

    def list(self, server_id: str) -> builtins.list[GameServerBackupResource]:
        """List backups.

        Required permissions:
            - `game_servers.backups.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_backups_list"),
        )
        return [GameServerBackupResource._from_dict(item) for item in response.json()]

    def create(
        self,
        server_id: str,
        *,
        body: GameServerBackupCreateRequest | None | dict[str, Any] | None = None,
    ) -> GameServerBackupResource:
        """Create backup.

        Required permissions:
            - `game_servers.backups.create`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_backups_create"),
        )
        return GameServerBackupResource._from_dict(response.json())

    def get_settings(self, server_id: str) -> GameServerBackupSettingsResource:
        """Get backup settings.

        Required permissions:
            - `game_servers.backups.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups/settings"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_backups_settings_list"),
        )
        return GameServerBackupSettingsResource._from_dict(response.json())

    def update_settings(
        self,
        server_id: str,
        *,
        body: GameServerBackupSettingsUpdateRequest | dict[str, Any],
    ) -> GameServerBackupSettingsResource:
        """Update backup settings.

        Required permissions:
            - `game_servers.backups.create`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups/settings"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_backups_settings_update"),
        )
        return GameServerBackupSettingsResource._from_dict(response.json())

    def delete(self, server_id: str, backup_id: str) -> None:
        """Delete backup.

        Required permissions:
            - `game_servers.backups.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups/{_quote_path(str(backup_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_backups_delete"),
        )
        return None

    def download(
        self, server_id: str, backup_id: str, *, component_id: str
    ) -> RedirectResponse:
        """Redirect an authorized browser to one selected backup component.

        Required permissions:
            - `game_servers.backups.download`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/backups/{_quote_path(str(backup_id), safe='')}/download"
        params = _filter_none(
            {
                "component_id": component_id,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_backups_download_list"),
        )
        location = response.headers.get("location")
        if not location:
            raise ApiError(
                status_code=response.status_code,
                code="MISSING_LOCATION",
                detail="Missing Location header in redirect response",
                operation=_OPERATION_BY_ID.get("servers_backups_download_list"),
            )
        return RedirectResponse(url=location)


class ServersConsoleService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get_token(self, server_id: str) -> GameServerConsoleTokenResource:
        """Return a short-lived WebSocket token for the server's console.

        Required permissions:
            - `game_servers.console.access`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/console/token"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_console_token_list"),
        )
        return GameServerConsoleTokenResource._from_dict(response.json())


class ServersDatabasesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(self, server_id: str) -> builtins.list[GameServerDatabaseListItemResource]:
        """List databases.

        Required permissions:
            - `game_servers.databases.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/databases"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_databases_list"),
        )
        return [
            GameServerDatabaseListItemResource._from_dict(item)
            for item in response.json()
        ]

    def create(
        self, server_id: str, *, body: GameServerDatabaseCreateRequest | dict[str, Any]
    ) -> GameServerDatabaseResource:
        """Create database.

        Required permissions:
            - `game_servers.databases.create`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/databases"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_databases_create"),
        )
        return GameServerDatabaseResource._from_dict(response.json())

    def delete(
        self,
        server_id: str,
        database_id: str,
        *,
        body: GameServerDatabaseDeleteRequest | dict[str, Any],
    ) -> None:
        """Delete database.

        Required permissions:
            - `game_servers.databases.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/databases/{_quote_path(str(database_id), safe='')}"
        json_payload = _serialize_body(body)
        self._client._request(
            "DELETE",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_databases_delete"),
        )
        return None

    def get(self, server_id: str, database_id: str) -> GameServerDatabaseResource:
        """Get database.

        Required permissions:
            - `game_servers.databases.credentials.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/databases/{_quote_path(str(database_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_databases_get"),
        )
        return GameServerDatabaseResource._from_dict(response.json())

    def reset_password(
        self, server_id: str, database_id: str
    ) -> GameServerDatabaseResource:
        """Reset database password.

        Required permissions:
            - `game_servers.databases.credentials.reset`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/databases/{_quote_path(str(database_id), safe='')}/password"
        response = self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_databases_password_create"),
        )
        return GameServerDatabaseResource._from_dict(response.json())


class ServersDomainService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def delete(self, server_id: str) -> None:
        """Delete server domain.

        Required permissions:
            - `game_servers.domains.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/domain"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_domain_delete"),
        )
        return None

    def get(self, server_id: str) -> ServerDomainResource | None:
        """Get server domain.

        Required permissions:
            - `game_servers.domains.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/domain"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_domain_list"),
        )
        return ServerDomainResource._from_dict(response.json())

    def list_options(
        self, server_id: str
    ) -> builtins.list[ManagedDomainOptionResource]:
        """List server domain options.

        Required permissions:
            - `game_servers.domains.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/domain/options"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_domain_options_list"),
        )
        return [
            ManagedDomainOptionResource._from_dict(item) for item in response.json()
        ]

    def set_subdomain(
        self, server_id: str, *, body: ServerSubdomainRequest | dict[str, Any]
    ) -> ServerDomainResource:
        """Set server subdomain.

        Required permissions:
            - `game_servers.domains.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/domain/subdomain"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_domain_subdomain_create"),
        )
        return ServerDomainResource._from_dict(response.json())


class ServersFilesCompressService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def create(
        self, server_id: str, *, body: FileCompressRequest | dict[str, Any]
    ) -> AxonOperationResource:
        """Compress files.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/compress"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_compress_create"),
        )
        return AxonOperationResource._from_dict(response.json())


class ServersFilesContentsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get(self, server_id: str, *, file: str) -> FileContentsResource:
        """Read file contents.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/contents"
        params = _filter_none(
            {
                "file": file,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_files_contents_list"),
        )
        return FileContentsResource._from_dict(response.json())

    def write(self, server_id: str, *, file: str, content: bytes | str) -> None:
        """Write file contents.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/contents"
        params = _filter_none(
            {
                "file": file,
            }
        )
        content_payload = content
        self._client._request(
            "POST",
            path,
            params=params,
            content=content_payload,
            operation=_OPERATION_BY_ID.get("servers_files_contents_create"),
        )
        return None


class ServersFilesDecompressService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def create(
        self, server_id: str, *, body: FileDecompressRequest | dict[str, Any]
    ) -> AxonOperationResource:
        """Decompress file.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/decompress"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_decompress_create"),
        )
        return AxonOperationResource._from_dict(response.json())

    def get_active(self, server_id: str) -> AxonOperationResource | None:
        """Get active decompress operation.

        Required permissions:
            - `game_servers.files.read`
        """
        path = (
            f"/servers/{_quote_path(str(server_id), safe='')}/files/decompress/active"
        )
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_files_decompress_active_list"),
        )
        return AxonOperationResource._from_dict(response.json())

    def get(self, server_id: str, operation_id: str) -> AxonOperationResource:
        """Get decompress operation.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/decompress/{_quote_path(str(operation_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_files_decompress_get"),
        )
        return AxonOperationResource._from_dict(response.json())

    def cancel(self, server_id: str, operation_id: str) -> AxonOperationResource:
        """Cancel decompress operation.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/decompress/{_quote_path(str(operation_id), safe='')}/cancel"
        response = self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_files_decompress_cancel_create"),
        )
        return AxonOperationResource._from_dict(response.json())


class ServersFilesSearchService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get(
        self,
        server_id: str,
        *,
        category: str | None = None,
        directory: str | None = None,
        extension: str | None = None,
        limit: int | None = None,
        max_size: int | None = None,
        min_size: int | None = None,
        modified_after: int | None = None,
        modified_before: int | None = None,
        offset: int | None = None,
        query: str | None = None,
        recursive: bool | None = None,
        search_id: str,
        sort: str | None = None,
        sort_desc: bool | None = None,
        type: str | None = None,
    ) -> FileSearchResource:
        """Search files.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/search"
        params = _filter_none(
            {
                "category": category,
                "directory": directory,
                "extension": extension,
                "limit": limit,
                "max_size": max_size,
                "min_size": min_size,
                "modified_after": modified_after,
                "modified_before": modified_before,
                "offset": offset,
                "query": query,
                "recursive": recursive,
                "search_id": search_id,
                "sort": sort,
                "sort_desc": sort_desc,
                "type": type,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_files_search_list"),
        )
        return FileSearchResource._from_dict(response.json())

    def cancel(self, server_id: str, search_id: str) -> None:
        """Cancel file search.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/search/{_quote_path(str(search_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_files_search_delete"),
        )
        return None


class ServersFilesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.compress = ServersFilesCompressService(client)
        self.contents = ServersFilesContentsService(client)
        self.decompress = ServersFilesDecompressService(client)
        self.search = ServersFilesSearchService(client)

    def list(
        self,
        server_id: str,
        *,
        directory: str | None = None,
        page_size: int | None = None,
        page_token: str | None = None,
        sort: str | None = None,
        sort_desc: bool | None = None,
    ) -> FileListResource:
        """List files.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files"
        params = _filter_none(
            {
                "directory": directory,
                "page_size": page_size,
                "page_token": page_token,
                "sort": sort,
                "sort_desc": sort_desc,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_files_list"),
        )
        return FileListResource._from_dict(response.json())

    def delete(
        self, server_id: str, *, body: FileDeleteRequest | dict[str, Any]
    ) -> None:
        """Delete files.

        Required permissions:
            - `game_servers.files.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/delete"
        json_payload = _serialize_body(body)
        self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_delete_create"),
        )
        return None

    def create_directories(
        self, server_id: str, *, body: FileCreateDirectoriesRequest | dict[str, Any]
    ) -> None:
        """Create directories.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/directories"
        json_payload = _serialize_body(body)
        self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_directories_create"),
        )
        return None

    def create_directory(
        self, server_id: str, *, body: FileCreateDirectoryRequest | dict[str, Any]
    ) -> None:
        """Create directory.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/directory"
        json_payload = _serialize_body(body)
        self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_directory_create"),
        )
        return None

    def get_download_url(self, server_id: str, *, file: str) -> FileUrlResource:
        """Get download url.

        Required permissions:
            - `game_servers.files.read`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/download-url"
        params = _filter_none(
            {
                "file": file,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_files_download_url_list"),
        )
        return FileUrlResource._from_dict(response.json())

    def rename(
        self, server_id: str, *, body: FileRenameRequest | dict[str, Any]
    ) -> None:
        """Rename file.

        Required permissions:
            - `game_servers.files.write`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/files/rename"
        json_payload = _serialize_body(body)
        self._client._request(
            "PUT",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_files_rename_update"),
        )
        return None


class ServersFoldersService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def create(
        self, *, body: GameServerFolderCreateRequest | dict[str, Any]
    ) -> GameServerFolderResource:
        """Create folder.

        Required permissions:
            - `game_servers.folders.manage`
        """
        path = "/servers/folders"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_folders_create"),
        )
        return GameServerFolderResource._from_dict(response.json())

    def get_tree(self) -> GameServerSidebarTreeResource:
        """Get folder tree.

        Required permissions:
            - `game_servers.folders.view`
        """
        path = "/servers/folders/tree"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_folders_tree_list"),
        )
        return GameServerSidebarTreeResource._from_dict(response.json())

    def delete(self, folder_id: str) -> None:
        """Delete folder.

        Required permissions:
            - `game_servers.folders.manage`
        """
        path = f"/servers/folders/{_quote_path(str(folder_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_folders_delete"),
        )
        return None

    def update(
        self, folder_id: str, *, body: GameServerFolderUpdateRequest | dict[str, Any]
    ) -> GameServerFolderResource:
        """Update folder.

        Required permissions:
            - `game_servers.folders.manage`
        """
        path = f"/servers/folders/{_quote_path(str(folder_id), safe='')}"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_folders_update"),
        )
        return GameServerFolderResource._from_dict(response.json())

    def remove_server(self, folder_id: str, server_id: str) -> None:
        """Remove server from folder.

        Required permissions:
            - `game_servers.folders.manage`
        """
        path = f"/servers/folders/{_quote_path(str(folder_id), safe='')}/servers/{_quote_path(str(server_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_folders_delete_1"),
        )
        return None

    def add_server(self, folder_id: str, server_id: str) -> None:
        """Assign server to folder.

        Required permissions:
            - `game_servers.folders.manage`
        """
        path = f"/servers/folders/{_quote_path(str(folder_id), safe='')}/servers/{_quote_path(str(server_id), safe='')}"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_folders_create_1"),
        )
        return None


class ServersInvitesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(self, server_id: str) -> builtins.list[ServerInviteResource]:
        """List server invites.

        Required permissions:
            - `game_servers.subusers.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/invites"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_invites_list"),
        )
        return [ServerInviteResource._from_dict(item) for item in response.json()]

    def create(
        self, server_id: str, *, body: GameServerInviteCreateRequest | dict[str, Any]
    ) -> ServerInviteResource:
        """Create server invite.

        Required permissions:
            - `game_servers.subusers.create`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/invites"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_invites_create"),
        )
        return ServerInviteResource._from_dict(response.json())

    def delete(self, server_id: str, invite_id: str) -> None:
        """Revoke server invite.

        Required permissions:
            - `game_servers.subusers.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/invites/{_quote_path(str(invite_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_invites_delete"),
        )
        return None


class ServersMinecraftInstallerService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list_engines(self, server_id: str) -> builtins.list[JsonObjectOutput]:
        """List Minecraft engines available for this server's cell images.

        Required permissions:
            - `game_servers.power.reinstall`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/features/minecraft-server-installer/catalog/engines"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get(
                "servers_features_minecraft_server_installer_catalog_engines_list"
            ),
        )
        return response.json()

    def list_versions(
        self,
        server_id: str,
        engine: str,
        *,
        include_archived: bool | None = None,
        search: str | None = None,
    ) -> builtins.list[JsonObjectOutput]:
        """List Minecraft versions compatible with this server's cell images.

        Required permissions:
            - `game_servers.power.reinstall`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/features/minecraft-server-installer/catalog/engines/{_quote_path(str(engine), safe='')}/versions"
        params = _filter_none(
            {
                "include_archived": include_archived,
                "search": search,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get(
                "servers_features_minecraft_server_installer_catalog_engines_versions_list"
            ),
        )
        return response.json()

    def list_builds(
        self,
        server_id: str,
        engine: str,
        version: str,
        *,
        include_archived: bool | None = None,
    ) -> builtins.list[JsonObjectOutput]:
        """List Minecraft builds compatible with this server's cell images.

        Required permissions:
            - `game_servers.power.reinstall`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/features/minecraft-server-installer/catalog/engines/{_quote_path(str(engine), safe='')}/versions/{_quote_path(str(version), safe='')}/builds"
        params = _filter_none(
            {
                "include_archived": include_archived,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get(
                "servers_features_minecraft_server_installer_catalog_engines_versions_builds_list"
            ),
        )
        return response.json()

    def reinstall(
        self,
        server_id: str,
        *,
        body: MinecraftInstallerReinstallRequest | dict[str, Any],
    ) -> None:
        """Reinstall Minecraft server.

        Required permissions:
            - `game_servers.power.reinstall`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/features/minecraft-server-installer/reinstall"
        json_payload = _serialize_body(body)
        self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get(
                "servers_features_minecraft_server_installer_reinstall_create"
            ),
        )
        return None


class ServersOperationsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(
        self, server_id: str, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedResponseAxonOperationResource:
        """List operations.

        Required permissions:
            - `game_servers.operations.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/operations"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_operations_list"),
        )
        return PaginatedResponseAxonOperationResource._from_dict(response.json())

    def get(self, server_id: str, operation_id: str) -> AxonOperationResource:
        """Get operation.

        Required permissions:
            - `game_servers.operations.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/operations/{_quote_path(str(operation_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_operations_get"),
        )
        return AxonOperationResource._from_dict(response.json())

    def cancel(self, server_id: str, operation_id: str) -> AxonOperationResource:
        """Cancel operation.

        Required permissions:
            - `game_servers.operations.cancel`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/operations/{_quote_path(str(operation_id), safe='')}/cancel"
        response = self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_operations_cancel_create"),
        )
        return AxonOperationResource._from_dict(response.json())


class ServersPowerService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def kill(self, server_id: str) -> None:
        """Force-kill the game server container.

        Required permissions:
            - `game_servers.power.kill`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/power/kill"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_power_kill_create"),
        )
        return None

    def reinstall(self, server_id: str) -> None:
        """Run the game server installer again without wiping server data.

        Required permissions:
            - `game_servers.power.reinstall`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/power/reinstall"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_power_reinstall_create"),
        )
        return None

    def restart(self, server_id: str) -> None:
        """Restart the game server container.

        Required permissions:
            - `game_servers.power.restart`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/power/restart"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_power_restart_create"),
        )
        return None

    def start(self, server_id: str) -> None:
        """Start the game server container.

        Required permissions:
            - `game_servers.power.start`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/power/start"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_power_start_create"),
        )
        return None

    def stop(self, server_id: str) -> None:
        """Stop the game server container.

        Required permissions:
            - `game_servers.power.stop`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/power/stop"
        self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_power_stop_create"),
        )
        return None


class ServersSchedulesRunsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(
        self,
        server_id: str,
        schedule_id: str,
        *,
        limit: int | None = None,
        offset: int | None = None,
    ) -> PaginatedResponseGameServerScheduleRunResource:
        """List schedule runs.

        Required permissions:
            - `game_servers.schedules.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules/{_quote_path(str(schedule_id), safe='')}/runs"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_schedules_runs_list"),
        )
        return PaginatedResponseGameServerScheduleRunResource._from_dict(
            response.json()
        )


class ServersSchedulesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.runs = ServersSchedulesRunsService(client)

    def list(
        self, server_id: str, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedResponseGameServerScheduleResource:
        """List schedules.

        Required permissions:
            - `game_servers.schedules.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_schedules_list"),
        )
        return PaginatedResponseGameServerScheduleResource._from_dict(response.json())

    def create(
        self, server_id: str, *, body: GameServerScheduleCreateRequest | dict[str, Any]
    ) -> GameServerScheduleResource:
        """Create schedule.

        Required permissions:
            - `game_servers.schedules.create`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_schedules_create"),
        )
        return GameServerScheduleResource._from_dict(response.json())

    def delete(self, server_id: str, schedule_id: str) -> None:
        """Delete schedule.

        Required permissions:
            - `game_servers.schedules.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules/{_quote_path(str(schedule_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_schedules_delete"),
        )
        return None

    def get(self, server_id: str, schedule_id: str) -> GameServerScheduleResource:
        """Get schedule.

        Required permissions:
            - `game_servers.schedules.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules/{_quote_path(str(schedule_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_schedules_get"),
        )
        return GameServerScheduleResource._from_dict(response.json())

    def update(
        self,
        server_id: str,
        schedule_id: str,
        *,
        body: GameServerScheduleUpdateRequest | dict[str, Any],
    ) -> GameServerScheduleResource:
        """Update schedule.

        Required permissions:
            - `game_servers.schedules.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules/{_quote_path(str(schedule_id), safe='')}"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_schedules_update"),
        )
        return GameServerScheduleResource._from_dict(response.json())

    def run(self, server_id: str, schedule_id: str) -> GameServerScheduleRunResource:
        """Run schedule.

        Required permissions:
            - `game_servers.schedules.run`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/schedules/{_quote_path(str(schedule_id), safe='')}/run"
        response = self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_schedules_run_create"),
        )
        return GameServerScheduleRunResource._from_dict(response.json())


class ServersSftpService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get_credentials(self, server_id: str) -> GameServerSftpCredentialsResource:
        """Get sftp credentials.

        Required permissions:
            - `game_servers.sftp.access`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/sftp/credentials"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_sftp_credentials_list"),
        )
        return GameServerSftpCredentialsResource._from_dict(response.json())

    def rotate_credentials(self, server_id: str) -> GameServerSftpCredentialsResource:
        """Rotate sftp credentials.

        Required permissions:
            - `game_servers.sftp.access`
        """
        path = (
            f"/servers/{_quote_path(str(server_id), safe='')}/sftp/credentials/rotate"
        )
        response = self._client._request(
            "POST",
            path,
            operation=_OPERATION_BY_ID.get("servers_sftp_credentials_rotate_create"),
        )
        return GameServerSftpCredentialsResource._from_dict(response.json())


class ServersStartupService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def get(self, server_id: str) -> GameServerStartupSettingsResource:
        """Return startup settings and editable options for a server.

        Required permissions:
            - `game_servers.startup.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/startup"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_startup_list"),
        )
        return GameServerStartupSettingsResource._from_dict(response.json())

    def update(
        self, server_id: str, *, body: GameServerStartupUpdateRequest | dict[str, Any]
    ) -> GameServerStartupSettingsResource:
        """Update user-controlled startup parameters.

        Required permissions:
            - `game_servers.startup.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/startup"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_startup_update"),
        )
        return GameServerStartupSettingsResource._from_dict(response.json())


class ServersSubusersService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def list(self, server_id: str) -> builtins.list[GameServerSubuserResource]:
        """List subusers.

        Required permissions:
            - `game_servers.subusers.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/subusers"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_subusers_list"),
        )
        return [GameServerSubuserResource._from_dict(item) for item in response.json()]

    def delete(self, server_id: str, access_id: str) -> None:
        """Delete subuser.

        Required permissions:
            - `game_servers.subusers.delete`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/subusers/{_quote_path(str(access_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("servers_subusers_delete"),
        )
        return None

    def update(
        self,
        server_id: str,
        access_id: str,
        *,
        body: GameServerSubuserUpdateRequest | dict[str, Any],
    ) -> GameServerSubuserResource:
        """Update subuser.

        Required permissions:
            - `game_servers.subusers.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}/subusers/{_quote_path(str(access_id), safe='')}"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_subusers_update"),
        )
        return GameServerSubuserResource._from_dict(response.json())


class ServersService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.activity = ServersActivityService(client)
        self.allocations = ServersAllocationsService(client)
        self.backups = ServersBackupsService(client)
        self.console = ServersConsoleService(client)
        self.databases = ServersDatabasesService(client)
        self.domain = ServersDomainService(client)
        self.files = ServersFilesService(client)
        self.folders = ServersFoldersService(client)
        self.invites = ServersInvitesService(client)
        self.minecraft_installer = ServersMinecraftInstallerService(client)
        self.operations = ServersOperationsService(client)
        self.power = ServersPowerService(client)
        self.schedules = ServersSchedulesService(client)
        self.sftp = ServersSftpService(client)
        self.startup = ServersStartupService(client)
        self.subusers = ServersSubusersService(client)

    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        search: str | None = None,
    ) -> PaginatedResponseGameServerListItemResource:
        """List game servers owned by or shared with the authenticated user.

        Required permissions:
            - `game_servers.view`
        """
        path = "/servers"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
                "search": search,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("servers_list"),
        )
        return PaginatedResponseGameServerListItemResource._from_dict(response.json())

    def get_overview(self) -> ServersOverviewResource:
        """Return status counts and a compact preview of owned and shared servers.

        Required permissions:
            - `game_servers.view`
        """
        path = "/servers/overview"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_overview_list"),
        )
        return ServersOverviewResource._from_dict(response.json())

    def get_usage(self) -> dict[str, GameServerUsageResource | None]:
        """Live Axon stats for accessible servers with usage permission, keyed by server UUID.

        Required permissions:
            - `game_servers.usage.view`
        """
        path = "/servers/usage"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_usage_list"),
        )
        return response.json()

    def get(self, server_id: str) -> GameServerDetailResource:
        """Return a single game server accessible to the authenticated user.

        Required permissions:
            - `game_servers.view`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("servers_get"),
        )
        return GameServerDetailResource._from_dict(response.json())

    def update(
        self, server_id: str, *, body: GameServerUpdateRequest | dict[str, Any]
    ) -> GameServerDetailResource:
        """Update owner-controlled server metadata.

        Required permissions:
            - `game_servers.settings.update`
        """
        path = f"/servers/{_quote_path(str(server_id), safe='')}"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("servers_update"),
        )
        return GameServerDetailResource._from_dict(response.json())


class TicketsMessagesAttachmentsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client

    def create(
        self, ticket_id: str, message_id: str, *, file: Upload | Any
    ) -> TicketAttachmentResource:
        """Upload a file attachment to a message.

        Required permissions:
            - `tickets.attachments.create`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/messages/{_quote_path(str(message_id), safe='')}/attachments"
        files_payload = _prepare_upload(file)
        response = self._client._request(
            "POST",
            path,
            files=files_payload,
            operation=_OPERATION_BY_ID.get("tickets_messages_attachments_create"),
        )
        return TicketAttachmentResource._from_dict(response.json())

    def delete(self, ticket_id: str, message_id: str, attachment_id: str) -> None:
        """Delete an attachment from a ticket message.

        Required permissions:
            - `tickets.attachments.delete`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/messages/{_quote_path(str(message_id), safe='')}/attachments/{_quote_path(str(attachment_id), safe='')}"
        self._client._request(
            "DELETE",
            path,
            operation=_OPERATION_BY_ID.get("tickets_messages_attachments_delete"),
        )
        return None

    def get_url(
        self, ticket_id: str, message_id: str, attachment_id: str
    ) -> dict[str, str]:
        """Return a presigned download URL (valid 1 hour).

        Required permissions:
            - `tickets.attachments.read`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/messages/{_quote_path(str(message_id), safe='')}/attachments/{_quote_path(str(attachment_id), safe='')}/url"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("tickets_messages_attachments_url_list"),
        )
        return response.json()


class TicketsMessagesService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.attachments = TicketsMessagesAttachmentsService(client)

    def list(
        self, ticket_id: str, *, before: str | None = None, limit: int | None = None
    ) -> builtins.list[TicketMessageResource]:
        """Paginate messages (cursor-based, newest-last).

        Required permissions:
            - `tickets.read`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/messages"
        params = _filter_none(
            {
                "before": before,
                "limit": limit,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("tickets_messages_list"),
        )
        return [TicketMessageResource._from_dict(item) for item in response.json()]

    def create(
        self, ticket_id: str, *, body: TicketMessageCreateRequest | dict[str, Any]
    ) -> TicketMessageResource:
        """Send a message to the ticket.

        Required permissions:
            - `tickets.messages.create`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/messages"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("tickets_messages_create"),
        )
        return TicketMessageResource._from_dict(response.json())


class TicketsService:
    def __init__(self, client: Any) -> None:
        self._client: Any = client
        self.messages = TicketsMessagesService(client)

    def list(
        self, *, limit: int | None = None, offset: int | None = None
    ) -> PaginatedResponseTicketResource:
        """List current user's own tickets.

        Required permissions:
            - `tickets.read`
        """
        path = "/tickets"
        params = _filter_none(
            {
                "limit": limit,
                "offset": offset,
            }
        )
        response = self._client._request(
            "GET",
            path,
            params=params,
            operation=_OPERATION_BY_ID.get("tickets_list"),
        )
        return PaginatedResponseTicketResource._from_dict(response.json())

    def create(self, *, body: TicketCreateRequest | dict[str, Any]) -> TicketResource:
        """Open a new support ticket. Limited to 5 open tickets per user at a time.

        Required permissions:
            - `tickets.create`
        """
        path = "/tickets"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "POST",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("tickets_create"),
        )
        return TicketResource._from_dict(response.json())

    def get_overview(self) -> TicketsOverviewResource:
        """Return current user's total number of non-terminal tickets.

        Required permissions:
            - `tickets.read`
        """
        path = "/tickets/overview"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("tickets_overview_list"),
        )
        return TicketsOverviewResource._from_dict(response.json())

    def get(self, ticket_id: str) -> TicketDetailResource:
        """Get ticket details and participants.

        Required permissions:
            - `tickets.read`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}"
        response = self._client._request(
            "GET",
            path,
            operation=_OPERATION_BY_ID.get("tickets_get"),
        )
        return TicketDetailResource._from_dict(response.json())

    def update_status(
        self, ticket_id: str, *, body: TicketStatusUpdateRequest | dict[str, Any]
    ) -> TicketResource:
        """Update ticket status.

        Required permissions:
            - `tickets.status.update`
        """
        path = f"/tickets/{_quote_path(str(ticket_id), safe='')}/status"
        json_payload = _serialize_body(body)
        response = self._client._request(
            "PATCH",
            path,
            json=json_payload,
            operation=_OPERATION_BY_ID.get("tickets_status_update"),
        )
        return TicketResource._from_dict(response.json())


class _GeneratedServicesMixin:
    def __init__(self, client: Any = None) -> None:
        c = client if client is not None else self
        self.game_features = GameFeaturesService(c)
        self.games = GamesService(c)
        self.order = OrderService(c)
        self.servers = ServersService(c)
        self.tickets = TicketsService(c)
