# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.29.194014
# sha256: dd1c161a1afa03fd4f86ad5486f65fac1c05f26740d3a9bf2ea338fee15402bb
from __future__ import annotations

from typing import TypeAlias

JsonObjectInput: TypeAlias = "dict[str, JsonValueInput]"


JsonObjectOutput: TypeAlias = "dict[str, JsonValueOutput]"


JsonScalar: TypeAlias = str | int | float | bool | None


JsonValueInput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueInput] | list[JsonValueInput]"
)


JsonValueOutput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueOutput] | list[JsonValueOutput]"
)
