# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.30.131845
# sha256: d5d7834ea8211ad101397d1e5fcd68696438447e2c53a3b5bdbc84941af59db4
from __future__ import annotations

from typing import TypeAlias

JsonObjectInput: TypeAlias = "dict[str, JsonValueInput]"


JsonObjectOutput: TypeAlias = "dict[str, JsonValueOutput]"


JsonScalar: TypeAlias = str | int | float | bool | None


JsonValueInput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueInput] | list[JsonValueInput]"
)


JsonValueOutput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueOutput] | list[JsonValueOutput]"
)
