# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: dev
# OpenAPI source: https://beta-api.hostero.gg/v1/openapi.json
# release: v2026.08.29.202831
# sha256: 6510f4a29ceccbda3e19f012a7daade7e575cdb5b94b76f786c439213513041e
from __future__ import annotations

from typing import TypeAlias

JsonObjectInput: TypeAlias = "dict[str, JsonValueInput]"


JsonObjectOutput: TypeAlias = "dict[str, JsonValueOutput]"


JsonScalar: TypeAlias = str | int | float | bool | None


JsonValueInput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueInput] | list[JsonValueInput]"
)


JsonValueOutput: TypeAlias = (
    "JsonScalar | dict[str, JsonValueOutput] | list[JsonValueOutput]"
)
