# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: test
# OpenAPI: ./openapi/hostero.openapi.json
# release: mvp
# sha256: 03c46244b097e10690b86591c5619747855cc1a6cb7f76214c99daeb8648f4d4
from enum import Enum


class GameServerStatus(str, Enum):
    ERROR = "error"
    INSTALL_FAILED = "install_failed"
    INSTALLED = "installed"
    INSTALLING = "installing"
    RESTORING = "restoring"
    RUNNING = "running"
    STARTING = "starting"
    STOPPED = "stopped"
    STOPPING = "stopping"
    SUSPENDED = "suspended"
