# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: test
# OpenAPI: ./openapi/hostero.openapi.json
# release: mvp
# sha256: 03c46244b097e10690b86591c5619747855cc1a6cb7f76214c99daeb8648f4d4
from __future__ import annotations

from dataclasses import dataclass

from .enums import GameServerStatus


@dataclass(kw_only=True)
class GameServerLimits:
    cpu: int
    disk_mb: int
    max_allocations: int
    max_backups: int
    max_databases: int
    memory_mb: int


@dataclass(kw_only=True)
class GameServerListItem:
    expires_at: str | None
    game_name: str
    id: str
    limits: GameServerLimits
    name: str
    node_name: str
    permissions: list[str]
    primary_allocation: PrimaryAllocation | None
    scheduled_delete_at: str | None
    short_id: str
    status: GameServerStatus


@dataclass(kw_only=True)
class PaginatedGameServers:
    has_next: bool
    items: list[GameServerListItem]
    limit: int
    offset: int
    total: int


@dataclass(kw_only=True)
class PrimaryAllocation:
    ip: str
    port: int
    protocol: str


@dataclass(kw_only=True)
class ServerOverviewItem:
    id: str
    name: str
    short_id: str
    status: GameServerStatus


@dataclass(kw_only=True)
class ServersOverview:
    items: list[ServerOverviewItem]
    running: int
    stopped: int
    total: int
