# Code generated by Hostero DevKit; DO NOT EDIT.
# devkit: test
# OpenAPI source: https://api.example.test/openapi.json
# release: mvp
# sha256: 03c46244b097e10690b86591c5619747855cc1a6cb7f76214c99daeb8648f4d4
from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class Operation:
    operation_id: str
    method: str
    path: str
    required_permissions: tuple[str, ...]
    target_kinds: tuple[str, ...]


OPERATIONS: Final[tuple[Operation, ...]] = (
    Operation(
        operation_id="listGameServers",
        method="GET",
        path="/servers",
        required_permissions=("game_servers.view",),
        target_kinds=("game_server",),
    ),
    Operation(
        operation_id="getServersOverview",
        method="GET",
        path="/servers/overview",
        required_permissions=("game_servers.view",),
        target_kinds=("game_server",),
    ),
    Operation(
        operation_id="restartGameServer",
        method="POST",
        path="/servers/{server_id}/power/restart",
        required_permissions=("game_servers.power.restart",),
        target_kinds=("game_server",),
    ),
)
